# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-Mirror
version:      0.02
version_from: lib/Tk/Mirror.pm
installdirs:  site
requires:
    Net::DownloadMirror:           0
    Net::MirrorDir:                0
    Net::UploadMirror:             0
    Storable:                      0
    Tk:                            0
    Tk::Frame:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
